swagger: "2.0"
info:
  title: Share
  version: "1.0"
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /healthcheck:
    post:
      operationId: api_v1.healthcheck.health_check
      tags:
        - S3
      summary: The people data structure supported by the server application
      description: Read the list of people
      responses:
        200:
          description: A file has been uploaded succesfully

  /filename/{filename}:
    get:
      operationId: api_v1.s3.list_file
      tags:
        - S3
      summary: The people data structure supported by the server application
      description: Read the list of people
      parameters:
        - $ref: "#/parameters/parameter_filename"
      responses:
        200:
          description: A file has been listed succesfully
    post:
      operationId: api_v1.s3.upload_file
      tags:
        - S3
      summary: The people data structure supported by the server application
      description: Read the list of people
      parameters:
        - $ref: "#/parameters/parameter_filename"
      responses:
        200:
          description: A file has been listed succesfully


    delete:
      operationId: api_v1.s3.delete_file
      tags:
        - S3
      summary: The people data structure supported by the server application
      description: Read the list of people
      parameters:
        - $ref: "#/parameters/parameter_filename"
      responses:
        200:
          description: A file has been listed succesfully

  /filename/{filename}/all:
    get:
      operationId: api_v1.s3.list_files
      tags:
        - S3
      summary: The people data structure supported by the server application
      description: Read the list of people
      parameters:
        - $ref: "#/parameters/parameter_filename"
      responses:
        200:
          description: A file has been listed succesfully

parameters:
  parameter_filename:
    name: filename
    in: path
    type: string
    format: string
    x-example: csrcertificatetest
    required: true

#  parameter_s3_name:
#    name: s3_name
#    in: path
#    type: string
#    format: string
#    x-example: MyAWSbucket
#    required: false
#

